# CI/CD pipeline
name: Deploy
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        make install
    - name: Lint
      run: |
        make lint
    - name: Test
      run: |
        make lint
    - name: Docker
      run: |
        docker build -t fer2013_trainer .

# non possibile testing sui dati dato che non sono scaricabili dinamicamente
# esiste la azione Test per completezza ma nel concreto viene saltato ogni test su github