# CI/CD pipeline
name: Deploy
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        make install

    - name: Lint
      run: |
        make lint

    - name: Test
      run: |
        make test

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build Docker img
      run: |
        docker build -f Dockerfile.prod -t kag3/emotionlens:latest .
    - name: Push Docker image
      run: |
        docker push kag3/emotionlens:latest
    - name: Save Docker img as artifact
      run: |
        docker save kag3/emotionlens:latest -o emotionlens-latest.tar
    - name: Upload Docker image artifact
      uses: actions/upload-artifact@v4
      with:
        name: docker-image
        path: emotionlens-latest.tar